module.exports = {
    index:{
        name:'权限管理'
    },
    allChannels:{
        index:'menus.html',
        name:'所有频道',
        child:{
            menus:'菜单管理',
            roles:'角色管理',
            users:'用户管理'
        }
    },
    thirdPartyOperation:{
        index:'roles.html',
        name:'三方运营',
        child:{
            roles:'角色管理',
            users:'用户管理'
        }
    },
    messageCenter:{
        index:'roles.html',
        name:'消息中心',
        child:{
            roles:'角色管理',
            users:'用户管理'
        }
    },
    publicConfig:{
        index:'roles.html',
        name:'公共配置',
        child:{
            roles:'角色管理',
            users:'用户管理'
        }
    }
};
